// import verified from "./icons/verified.svg";
import chickenrepublic from "./icons/chickenrepublic.svg";
import mamadora from "./icons/mamadora.svg";
// import option from "../../Assets/Couriericons/options.svg";
export default [
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phone: null,
    amountSpent: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: mamadora },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Grocery",
    wallet: "N243,786.23",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: mamadora },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Grocery",
    wallet: "N243,786.23",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: mamadora },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Grocery",
    wallet: "N243,786.23",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: mamadora },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Grocery",
    wallet: "N243,786.23",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: mamadora },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Grocery",
    wallet: "N243,786.23",
  },
  {
    name: { title: "Tiamiyu Wasiu", icon: chickenrepublic },
    email: "tiamiyuwasiu@gmail.com",
    phonenumber: null,
    amountspend: null,
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: "Kitchen",
    wallet: "N160,000.00",
  },
];
