// import verified from "./icons/verified.svg";
import dp from "./icons/dp.svg";
// import option from "../../Assets/Couriericons/options.svg";
export default [
  {
    key: 1,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 2,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 3,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 4,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 5,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 6,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 7,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 8,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 9,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 10,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
  {
    key: 11,
    name: { title: "Tiamiyu Wasiu", icon: dp },
    email: "tiamiyuwasiu@gmail.com",
    phone: "08160178711",
    amountSpentspent: "#160,000.00",
    datejoined: "Feb.15,2024",
    status: "Verified",
    store: null,
    wallet: null,
  },
];
